site_name: LEAF Roleplay
site_description: 'Wet en regelgeving van LEAF roleplay'
site_url: https://leafroleplay.nl
repo_url: 'https://github.com/LeafRoleplay/LeafRoleplay'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.footer
  logo: leaf.png
  favicon: leaf.png
  palette:
   # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny 
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    
  language: nl

  nav: 
    - Home: index.md
    - LEAF Team: team.md
    - Algmene Regels: algemeen.md
    - Onderwereld Regels: onderwereld.md

  plugins:
  - offline
  

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/leafrp
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@iiStormz
  analytics:
    provider: google
    property: G-NV5M4K299L

  consent:
    title: Cookies
    description: >- 
      We gebruiken cookies om uw herhaalde bezoeken en voorkeuren te herkennen, en
      om de effectiviteit van onze documentatie te meten en of gebruikers
      vinden wat ze zoeken. Met uw toestemming helpt u ons om
      onze documentatie te verbeteren.
    actions:
      - accept
  
copyright: Copyright &copy; 2025 LEAF Roleplay - Alle rechten voorbehouden.
